% !git clone --depth=1 https://github.com/CSSEGISandData/COVID-19.git
% !gir remote add myOrigin git@github.com:nkyang/COVID-19.git
% !git fetch origin master
% !git push myOrigin master

addpath ../csse_covid_19_data/csse_covid_19_daily_reports
f = dir ('../csse_covid_19_data/csse_covid_19_daily_reports/*.csv');

ctyList = {'Argentina','Australia','Brazil','Canada','China',...
    'France','Germany','India','Indonesia','Italy',...
    'Japan','Korea, South','Mexico','Russia','Saudi Arabia',...
    'South Africa','Spain','Turkey','US','United Kingdom'};
ctyList_CN = {'阿根廷','澳大利亚','巴西','加拿大','中国',...
    '法国','德国','印度','印度尼西亚','意大利',...
    '日本','韩国','墨西哥','俄罗斯','沙特',...
    '南非','西班牙','土耳其','美国','英国'};
m = numel(f);
n = numel(ctyList);
dataTable = timetable('Size',[m 3*n],...
    'variableTypes',repmat("double",1,3*n),...
    'RowTimes',getDate(f));
warning('off');
for ii = 1:m
    data = getReport(f(ii).name,ctyList);
    dataTable{ii,:} = reshape(data,1,[]);
end
for ii = 1:n
    dataTable = mergevars(dataTable,ii:ii+2,...
        'NewVariableName',ctyList{ii});
end

%% 
v = VideoWriter('output','MPEG-4');
open(v);
%% 封面与结尾
figure('Position',[100 100 1280 720]);
ax = axes(gcf,'Visible','off');
text(ax,0.5,0.8,'本视频由\fontname{Times New Roman}MATLAB\fontname{宋体}程序自动生成',...
    'FontName','宋体','FontSize',24,'FontWeight','bold','HorizontalAlignment','center')
text(ax,0.5,0.7,'(https://github.com/nkyang/COVID-19)',...
    'FontName','Times New Roman','FontSize',20,'HorizontalAlignment','center')
text(ax,0.5,0.55,'更多内容见知乎文章','FontName','宋体',...
    'FontWeight','bold','FontSize',32,'HorizontalAlignment','center')
text(ax,0.5,0.45,'(易夕：用\fontname{Times New Roman}MATLAB\fontname{宋体}生成视频——追踪\fontname{Times New Roman}COVID-19\fontname{宋体}全球大流行)',...
    'FontWeight','bold','FontName','宋体','FontSize',20,'HorizontalAlignment','center')
text(ax,0.5,0.2,'数据来源：约翰霍普金斯大学','FontName','宋体','FontSize',20,'HorizontalAlignment','center');
text(ax,0.5,0.15,'(https://github.com/CSSEGISandData/COVID-19)',...
    'FontName','Times New Roman','FontSize',20,'HorizontalAlignment','center');
A = print('-RGBImage','-r0');
for ii = 1:30*3
    writeVideo(v,A);
end
%% 视频主体
barChartRace(v,dataTable,...
    'Position',[100 100 1280 720],...
    'DisplayFontSize',24,...
    'LabelNames',ctyList_CN,...
    'NumDisplay',20,...
    'NumInterp',15,...
    'XlabelName','累计确诊人数',...
    'GenerateMovie',1,...
    'Footnote','Visualized by 易夕');

%% 结尾
for ii = 1:30*3
    writeVideo(v,A);
end
close(v)
